### ISSUE TITLE
נושאים שצריך לגעת בהם

### ISSUE THREAD

**Issue by YMP112** [ynigun/open-book#4]
אולי כדאי לעשות רשימת נושאים שכדאי לגעת בהם
וכל מי שרוצה יכתוב וירחיב

**Comment by YMP112** [comment]
צמצמ

**Comment by ynigun** [comment]
נכון.
נראה לי שהכי פשוט להוסיף כותרות בדף הראשי

**Comment by YMP112** [comment]
גם אופציה
ואני מתנצל על כל הבלגן שאני עושה
אני וגיטהב עדיין בהיכרות

**Comment by ynigun** [comment]
@YMP112 
אתה יכול להרשם לקבלת התרעות על שינויים וכשיהיו שינויים לבדוק האם יש לך מה לתרום

**Comment by YMP112** [comment]
ואיך אני נרשם

**Comment by ynigun** [comment]
@YMP112 
בכפתור watch

**Comment by YMP112** [comment]
תודה רבה
אני סוגר את הנושא הזה
אם יש אפשרות למחוק אותו נראה לי שעדיף
